Feat/crud my user profile
blackmouse572/quizler-fe pull request #52
Opened 2024-03-20 15:39 UTC by pikaden

click 
![image](https://github.com/blackmouse572/quizler-fe/assets/87664605/404f28f8-08e4-417c-8ffc-2a78bb0f77b1)
to go to profile

Author can view their profile, update account, change preference (change locale)

If they view other's profile, they cannot do that.
![image](https://github.com/blackmouse572/quizler-fe/assets/87664605/2a8d46dc-ddcb-4b02-ab41-f5ec0b5d43e8)

Added link to user's profile in search global and view quizbank

2024-03-20 15:56 UTC, blackmouse572 requested changes

2024-03-20 15:56 UTC, blackmouse572 commented on src/app/[locale]/(main)/profile/[id]/components/locale-switcher-select.tsx
> +    </label>
https://ui.shadcn.com/docs/components/select

Use `<Select>` and `<Label>`

2024-03-20 15:56 UTC, blackmouse572 commented on src/app/[locale]/(main)/profile/[id]/components/navigation-menu.tsx
> +      <div className="ml-20 mt-5 fixed w-16 flex-col items-start self-start rounded-lg border border-solid border-neutral-300 bg-neutral-50 py-3 pl-3 shadow-md max-md:ml-2.5">
use `gap` to create space for children.

2024-03-21 03:11 UTC, pikaden commented on src/app/[locale]/(main)/profile/[id]/components/navigation-menu.tsx
> +            className="mt-2.5 flex h-10 w-10/12 justify-center gap-2.5 rounded-xl p-1.5 shadow-sm"
Updated: deleted and change to NamedTooltip

2024-03-21 03:46 UTC, blackmouse572 requested changes
all action server must be mark as "use server" and function have "action" as suffix (ex: getUserProfileAction())

2024-03-21 03:46 UTC, blackmouse572 commented on src/app/[locale]/(main)/profile/[id]/profile/actions/fetch-user-profile.tsx
> +import { getToken } from "@/lib/auth"
all action server must be mark as "use server" and function have "action" as suffix (ex: `getUserProfileAction()`)

2024-03-21 03:46 UTC, blackmouse572 commented on src/app/[locale]/(main)/profile/[id]/profile/actions/update-user-profile.tsx
> +  id,
all action server must be mark as "use server" and function have "action" as suffix (ex: getUserProfileAction())

2024-03-21 03:46 UTC, blackmouse572 commented on src/app/[locale]/(main)/profile/[id]/account/actions/change-password.tsx
> +export const ChangePassword = async ({
all action server must be mark as "use server" and function have "action" as suffix (ex: getUserProfileAction())

2024-03-21 08:42 UTC, blackmouse572 approved these changes

2024-03-21 08:42 UTC, merged