Feat/crud students classroom
blackmouse572/quizler-fe pull request #54
Opened 2024-03-22 08:33 UTC by pikaden

Login with account: 
user@example.com
string

Go to http://localhost:3000/classrooms/6/manage
User can remove 1 user
![image](https://github.com/blackmouse572/quizler-fe/assets/87664605/19be8973-8c35-48be-a0bf-71fd0edb71d4)

User can remove batch user
![image](https://github.com/blackmouse572/quizler-fe/assets/87664605/a7fbaeec-d560-45fb-9401-2812bcebac0f)

User can search

TODO:
classroom header
invite student by code, by email
navigation menu

2024-03-22 08:36 UTC, pikaden commented
Need to authorization: there are 2 options:
1. Only teacher can access, and he can invite other student
2. Member and teacher can access, but only teacher can invite, default is isStudentAllowInvite

Header is only show classroom detail, and no button invite student in this table

2024-03-23 09:18 UTC, blackmouse572 requested changes
Nice work, just little adjustments

2024-03-23 09:18 UTC, blackmouse572 commented on src/app/[locale]/(main)/classrooms/[id]/manage/actions/get-all-members-action.ts
> +  return res
Following fetch backend pattern to make sure same result for every page. Ref for get-all-quizbank

2024-03-23 09:18 UTC, blackmouse572 commented on src/types/classroom.ts
> +
Isn't same as User type ?

2024-03-23 10:46 UTC, blackmouse572 approved these changes

2024-03-23 11:02 UTC, merged