[QLN-46] feat: add report user of violation rules
blackmouse572/quizler-fe pull request #92
Opened 2024-04-12 16:59 UTC by lilinkw

- Add report dialog
- Call API to BE
- Display result of report
![image](https://github.com/blackmouse572/quizler-fe/assets/81068699/3ba705e1-491e-4be0-8b03-c4c7c1cab8a8)
![image](https://github.com/blackmouse572/quizler-fe/assets/81068699/8a3485b9-ec66-401d-be2d-8b29f69ceae1)

2024-04-12 17:15 UTC, blackmouse572 requested changes

2024-04-12 17:15 UTC, blackmouse572 commented on messages/vi.json
> +      "thank_you_reported": "Thank you for your contribute for better learning space",
Change this

2024-04-12 17:15 UTC, blackmouse572 commented on src/app/[locale]/(main)/users/[id]/acitons/fetch-report-user.tsx
> +      revalidate: 60, // Revalidate every 60 second
POST dont cache

2024-04-12 17:15 UTC, blackmouse572 commented on src/app/[locale]/(main)/users/[id]/components/report-button.tsx
> +    </Tooltip>
use `NamedToolTip`

2024-04-12 17:15 UTC, blackmouse572 commented on src/app/[locale]/(main)/users/[id]/components/report-user-dialog/report-user-result-dialog.tsx
> +            </span>
This is Link

2024-04-12 17:21 UTC, lilinkw commented on src/app/[locale]/(main)/users/[id]/components/report-user-dialog/report-user-result-dialog.tsx
> +            </span>
Link to where?

2024-04-13 06:48 UTC, blackmouse572 approved these changes

2024-04-13 06:48 UTC, merged